version: '3.8'

services:
  backend:
    build:
      context: ./Backend/BibliotecaAPI
      dockerfile: Biblioteca.WebApi/Dockerfile
    ports:
      - "5130:8080"
      - "7155:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=biblioteca;Username=postgres;Password=postgres

  frontend:
    build:
      context: ./Frontend/BibliotecaVue
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=biblioteca
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
